- hosts: localhost
  gather_facts: false
  vars:
    secret: test
    namespace: osdk-test
  tasks:

    - name: Fetch controller secret
      k8s_facts:
        api_version: v1
        kind: Secret
        name: "{{ secret }}"
        namespace: "{{ namespace }}"
      register: secret
