apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mysqldatabases.mysql.glothriel.org
spec:
  group: mysql.glothriel.org
  names:
    kind: MySQLDatabase
    listKind: MySQLDatabaseList
    plural: mysqldatabases
    singular: mysqldatabase
  scope: Namespaced
  subresources:
    status: {}
  versions:
  - name: v1alpha1
    served: true
    storage: true
  validation:
    openAPIV3Schema:
      properties:
        metadata:
          properties:
            name:
              type: string
              minLength: 6
              maxLength: 16