---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: poc-mysql-operator
rules:

# # This, when uncommented fixes the problem
# - apiGroups:
#   - ""
#   resources:
#   - secrets
#   verbs:
#   - '*'
  
- apiGroups:
  - apps
  resourceNames:
  - poc-mysql-operator
  resources:
  - deployments/finalizers
  verbs:
  - update

- apiGroups:
  - mysql.glothriel.org
  resources:
  - '*'
  verbs:
  - '*'
