---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: poc-mysql-operator
subjects:
- kind: ServiceAccount
  namespace: "{{ namespace }}"
  name: poc-mysql-operator
roleRef:
  kind: ClusterRole
  name: poc-mysql-operator
  apiGroup: rbac.authorization.k8s.io
