apiVersion: apps/v1
kind: Deployment
metadata:
  name: poc-mysql-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: poc-mysql-operator
  template:
    metadata:
      labels:
        name: poc-mysql-operator
    spec:
      serviceAccountName: poc-mysql-operator
      containers:
        - name: ansible
          command:
          - /usr/local/bin/ao-logs
          - /tmp/ansible-operator/runner
          - stdout
          # Replace this with the built image name
          image: "{{ REPLACE_IMAGE }}"
          imagePullPolicy: "Never"
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
            readOnly: true
        - name: operator
          # Replace this with the built image name
          image: "{{ REPLACE_IMAGE }}"
          imagePullPolicy: "Never"
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "poc-mysql-operator"
            # # This, when uncommented fixes the problem
            # - name: WATCH_NAMESPACE
            #   value: "{{ namespace }}"
            - name: OPERATOR_CREDENTIALS_SECRET
              value: "mysql-admin-secret"
            - name: ANSIBLE_GATHERING
              value: explicit
      volumes:
        - name: runner
          emptyDir: {}
