---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: poc-mysql-operator
  namespace: "{{ namespace }}"
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - services/finalizers
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - '*'

- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - '*'

- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get

- apiGroups:
  - apps
  resources:
  - replicasets
  verbs:
  - get

- apiGroups:
  - mysql.glothriel.org
  resources:
  - '*'
  verbs:
  - 'get'
